# Safety policy file for packages needed for installation
# For documentation, see https://docs.pyup.io/docs/safety-20-policy-file

# Configuration for the 'safety check' command
security:

    # Ignore certain severities.
    # A number between 0 and 10, with the following significant values:
    # - 9: ignore all vulnerabilities except CRITICAL severity
    # - 7: ignore all vulnerabilities except CRITICAL & HIGH severity
    # - 4: ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity
    ignore-cvss-severity-below: 0

    # Ignore unknown severities.
    # Should be set to False.
    ignore-cvss-unknown-severity: False

    # List of specific vulnerabilities to ignore.
    # {id}:                 # vulnerability ID
    #     reason: {text}    # optional: Reason for ignoring it. Will be reported in the Safety reports
    #     expires: {date}   # optional: Date when this ignore will expire
    ignore-vulnerabilities:
        39611:
            reason: PyYAML full_load method or FullLoader is not used
        42923:
            reason: Fixed Ansible version is stated to be 0
        54229:
            reason: Not yet fixed in any ansible version, but need to support ansible 2.9
        54230:
            reason: Not yet fixed in any ansible version, but need to support ansible 2.9
        54564:
            reason: Fixed ansible version is 7.0.0, but need to support ansible 2.9
        63066:
            reason: Fixed ansible-core version 2.15.8 requires Python>=3.9 and is used on Python>=3.12
        65511:
            reason: Fixed ansible-core version 2.13.13 requires Python>=3.8 and 2.13.x is not used
        66667:
            reason: Fixed ansible-core version 2.12.0 requires Python>=3.8 and is used on Python>=3.10
        66700:
            reason: Fixed ansible-core version 2.14.14 requires Python>=3.9 and is used on Python>=3.11
        67599:
            reason: Disputed issue in pip version 23.3 - No known fix
        70612:
            reason: Disputed issue in jinja2 version 3.1.3 - No known fix
        70895:
            reason: Fixed ansible-core version 2.15.2 requires Python>=3.9 and is used on Python>=3.12

    # Continue with exit code 0 when vulnerabilities are found.
    continue-on-vulnerability-error: False
