namespace: ibm

name: ibm_zhmc

version: 1.11.0-dev1

readme: README.md

# Keep in sync with AUTHORS.md
authors:
  - Abhiram Santhosh <abhiram.santhosh1@ibm.com>
  - Adilet Sabyrbaev <adilet.sabyrbaev2@ibm.com>
  - Andreas Maier <maiera@de.ibm.com>
  - Andreas Scheuring <andreas.scheuring@de.ibm.com>
  - Anil Kumar Dakarapu <anil.kumar.dakarapu@ibm.com>
  - Demetrios Dimatos <dimatos@gmail.com>
  - Juergen Leopold <leopoldj@de.ibm.com>
  - Kathiravan Velusamy <kathir.velu@in.ibm.com>
  - Klaus Smolin <smolin@de.ibm.com>
  - Uday Kiran Reddy Konda <Uday.Kiran.Reddy.Konda@ibm.com>
  - Vance Morris <vmorris@us.ibm.com>

# Keep in sync with the overview description in README.md
description:
  This collection supports automation tasks on the IBM Z HMC such as creating,
  updating or deleting partitions, accesssing operating system messages,
  configuring adapters, managing HMC users, upgrading the SE and HMC firmware,
  and many more. It supports CPCs in classic mode and in DPM mode.

license:
  - "Apache-2.0"

# Ansible Automation Hub requires at least one tag from a standard tag list;
# this collection specifies 'infrastructure'.
tags:
  [
    ibm,
    z,
    dpm,
    hmc,
    infrastructure
  ]

# The URL of the originating SCM repository
repository: https://github.com/zhmcclient/zhmc-ansible-modules

# The URL to any online docs
documentation: https://zhmcclient.github.io/zhmc-ansible-modules/

# The URL to the homepage of the collection/project
homepage: https://github.com/zhmcclient/zhmc-ansible-modules

# The URL to the collection issue tracker
issues: https://github.com/zhmcclient/zhmc-ansible-modules/issues

# Ignore files and directories matching the following patterns
build_ignore:
  # Ignore items from .gitignore:
  - '*.DS_Store'
  - '*.pyc'
  - '*.pyo'
  - '*.egg'
  - '*.egg-info'
  - '*.done'
  - '*.log'
  - '*.retry'
  - '*.tmp'
  - 'vars.yml'
  - 'vault.yml'
  - try
  - 'try_*'
  - tmp
  - 'tmp_*'
  - .coverage
  - .pytest_cache
  - venv
  - htmlcov
  - dist
  - docs_linkcheck
  - docs_build
  - tests/output
  - AUTHORS  # only in older branches
  - AUTHORS.md
  - ChangeLog  # only in older branches
  - build  # only in older branches
  - gh-pages  # in case it exists locally
  # Other ignore items:
  - galaxy.yml
  - .github
  - .gh-pages-exclude
  - .gitignore
  - .coveragerc
  - .flake8  # only in older branches
  - .pylintrc
  - .travis.yml
  - .whitesource
  - .safety-policy-all.yml  # old name
  - .safety-policy-develop.yml  # old name
  - .safety-policy-install.yml
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.rst  # only in older branches
  - DCO1.1.txt  # only in older branches
  - LICENSE
  - Makefile
  # requirements.txt is intentionally included for dependent install
  - dev-requirements.txt  # old name
  - requirements-base.txt
  - requirements-develop.txt
  - ansible-constraints.txt
  - minimum-constraints.txt  # old name
  - minimum-constraints-install.txt  # old name
  - minimum-constraints-develop.txt  # old name
  - collections
  - tools
  - docs_local
  - docs
  - tests/end2end
  - tests/function
  - tests/unit
  - done
