namespace: ibm

name: ibm_zhmc

version: 1.0.2

readme: README.md

authors:
  - Andy Maier (@andy-maier)
  - Juergen Leopold (@leopoldjuergen)
  - Andreas Scheuring (@scheuran)
  - Kathiravan Velusamy (@vkahir)
  - Adilet Sabyrbaev (@sabyadi)

description: This collection can manage platform resources on IBM Z and LinuxONE machines, for example partitions, adapters, the Z system itself, or various resources on its Hardware Management Console (HMC).

license:
  - "Apache-2.0"

# Ansible Automation Hub requires at least one tag from a standard tag list;
# this collection specifies 'infrastructure'.
tags:
  [
    ibm,
    z,
    dpm,
    hmc,
    infrastructure
  ]

# The URL of the originating SCM repository
repository: https://github.com/zhmcclient/zhmc-ansible-modules

# The URL to any online docs
documentation: https://zhmcclient.github.io/zhmc-ansible-modules/

# The URL to the homepage of the collection/project
homepage: https://github.com/zhmcclient/zhmc-ansible-modules

# The URL to the collection issue tracker
issues: https://github.com/zhmcclient/zhmc-ansible-modules/issues

# Ignore files and directories matching the following patterns
build_ignore:
  # Ignore items from .gitignore:
  - '*.DS_Store'
  - '*.pyc'
  - '*.pyo'
  - '*.egg'
  - '*.egg-info'
  - '*.done'
  - '*.log'
  - '*.retry'
  - '*.tmp'
  - 'vars.yml'
  - 'vault.yml'
  - try
  - 'try_*'
  - tmp
  - 'tmp_*'
  - .coverage
  - .pytest_cache
  - venv
  - htmlcov
  - dist
  - docs_linkcheck
  - docs_build
  - tests/output
  - AUTHORS  # only in older branches
  - ChangeLog  # only in older branches
  - build  # only in older branches
  - gh-pages  # in case it exists locally
  # Other ignore items:
  - galaxy.yml
  - .github
  - .gh-pages-exclude
  - .gitignore
  - .coveragerc
  - .flake8  # only in older branches
  - .travis.yml
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.rst  # only in older branches
  - DCO1.1.txt  # only in older branches
  - LICENSE
  - Makefile
  # requirements.txt is intentionally included for dependent install
  - dev-requirements.txt
  - minimum-constraints.txt
  - tools
  - docs_local
