---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
    - vault.yml
  tasks:

  - name: Ensure domains 1-max on 1 adapter are attached in usage mode to partition 3
    zhmc_crypto_attachment:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      partition_name: "{{ partition3_name }}"
      state: attached
      crypto_type: ep11
      adapter_count: 1
      domain_range: 1,-1
      access_mode: usage
      log_file: crypto.log
    register: result

  - name: Print the result
    debug:
      var: result
