---
- hosts: localhost
  vars_files:
    - vars.yml
    - vault.yml
  collections:
  - ibm.zhmc
  tasks:

  - name: Ensure partition exists and is stopped
    zhmc_partition:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ partition_name }}"
      state: stopped
      properties:
        description: "zhmc Ansible modules: partition 1"
        ifl_processors: 2
        initial_memory: 1024
        maximum_memory: 1024
        minimum_ifl_processing_weight: 50
        maximum_ifl_processing_weight: 800
        initial_ifl_processing_weight: 200
    register: part1

  - name: Ensure HBA exists in the partition
    zhmc_hba:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      partition_name: "{{ partition_name }}"
      name: "{{ hba_name }}"
      state: present
      properties:
        adapter_name: "{{ hba_adapter_name }}"
        adapter_port: "{{ hba_adapter_port }}"
        description: The HBA to our storage
        device_number: "023F"
    register: hba1

  - name: Ensure NIC exists in the partition
    zhmc_nic:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      partition_name: "{{ partition_name }}"
      name: "{{ nic_name }}"
      state: present
      properties:
        adapter_name: "{{ nic_adapter_name }}"
        adapter_port: "{{ nic_adapter_port }}"
        description: The NIC to our data network
        device_number: "013F"
    register: nic1

  - name: Ensure virtual function exists in the partition
    zhmc_virtual_function:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      partition_name: "{{ partition_name }}"
      name: "{{ vfunction_name }}"
      state: present
      properties:
        adapter_name: "{{ vfunction_adapter_name }}"
        description: The virtual function for our accelerator adapter
        device_number: "043F"
    register: vfunction1

  - name: Configure partition for booting via HBA
    zhmc_partition:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ partition_name }}"
      state: stopped
      properties:
        boot_device: storage-adapter
        boot_storage_hba_name: "{{ hba_name }}"
        boot_logical_unit_number: "0001"
        boot_world_wide_port_name: "00cdef01abcdef01"
    register: part1

  - name: Ensure crypto config for partition
    zhmc_partition:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ partition_name }}"
      state: stopped
      properties:
        crypto_configuration:
          crypto_adapter_names:
            - "{{ crypto_adapter_name }}"
          crypto_domain_configurations:
            - domain_index: "17"
              access_mode: "control-usage"
            - domain_index: 20
              access_mode: "control"
    register: part1
