---
- hosts: localhost
  vars_files:
    - vars.yml
    - vault.yml
  tasks:

  - name: Ensure partition 1 for crypto use exists and is stopped
    zhmc_partition:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ partition_name }}"
      state: stopped
      properties:
        description: "zhmc Ansible modules: partition 1"
        ifl_processors: 2
        initial_memory: 1024
        maximum_memory: 1024
    register: part1

  - name: Ensure partition 2 for crypto use exists and is stopped
    zhmc_partition:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ partition2_name }}"
      state: stopped
      properties:
        description: "zhmc Ansible modules: partition 2"
        ifl_processors: 2
        initial_memory: 1024
        maximum_memory: 1024
    register: part2

  - name: Ensure partition 3 for crypto use exists and is stopped
    zhmc_partition:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ partition3_name }}"
      state: stopped
      properties:
        description: "zhmc Ansible modules: partition 3"
        ifl_processors: 2
        initial_memory: 1024
        maximum_memory: 1024
    register: part3
