---
- hosts: localhost
  vars_files:
    - vars.yml
    - vault.yml
  tasks:

  - name: Ensure a Hipersockets adapter does not exist
    zhmc_adapter:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ hs_adapter_name }}"
      state: absent
