---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
    - vault.yml
  tasks:

  - name: Ensure storage group is detached from partition
    zhmc_storage_group_attachment:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      storage_group_name: "{{ sg_name }}"
      partition_name: "{{ partition_name }}"
      state: detached
    register: result

  - name: Print the result
    debug:
      var: result
