---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
    - vault.yml
  tasks:

  - name: "Get facts about crypto config of partition {{ partition_name }}"
    zhmc_crypto_attachment:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      partition_name: "{{ partition_name }}"
      state: facts
      log_file: crypto.log
    register: result

  - name: Print the result
    debug:
      var: result
