---
- hosts: localhost
  vars_files:
    - vars.yml
    - vault.yml
  tasks:

  - name: Get CPC facts
    zhmc_cpc:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      name: "{{ cpc_name }}"
      state: facts
      log_file: cpc.log
    register: cpc1

#  - debug:
#      var: cpc1

  - debug:
      msg: "CPC description = '{{ cpc1['cpc']['description'] }}'"
