---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
    - vault.yml
  tasks:

  - name: Get storage group facts
    zhmc_storage_group:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ sg_name }}"
      state: facts
      expand: true
    register: result

  - name: Print the result
    debug:
      var: result
