---
- hosts: localhost
  vars_files:
    - vars.yml
    - vault.yml
  collections:
  - ibm.zhmc
  tasks:

  - name: Set CPC description
    zhmc_cpc:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      name: "{{ cpc_name }}"
      state: set
      properties:
        description: "This is CPC {{ cpc_name }}"
    register: result

  - name: Print the result
    debug:
      var: result
