---
- hosts: localhost
  vars_files:
    - vars.yml
    - vault.yml
  collections:
  - ibm.zhmc
  tasks:

  - name: Ensure partition does not exist
    zhmc_partition:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ partition_name }}"
      state: absent
    register: result

  - name: Print the result
    debug:
      var: result
