---
- hosts: localhost
  vars_files:
    - vars.yml
    - vault.yml
  collections:
  - ibm.ibm_zhmc
  tasks:

  - name: Ensure a Hipersockets adapter exists and has the desired property values
    zhmc_adapter:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      cpc_name: "{{ cpc_name }}"
      name: "{{ hs_adapter_name }}"
      state: present
      properties:
        type: hipersockets
        description: "This is Hipersockets adapter {{ hs_adapter_name }}"
    register: result

  - name: Print the result
    debug:
      var: result
