---
- hosts: localhost
  vars_files:
    - vars.yml
    - vault.yml
  collections:
  - ibm.zhmc
  tasks:

  - name: Get CPC facts
    zhmc_cpc:
      hmc_host: "{{ hmc_host }}"
      hmc_auth: "{{ hmc_auth }}"
      name: "{{ cpc_name }}"
      state: facts
    register: result

  - name: Print the result
    debug:
      var: result
