# This GitHub workflow will build the documentation and publish it on GitHub Pages.

name: pages

env:
  # Command that builds the documentation:
  doc_build_cmd: make docs
  # Directory where the documentation is built in main worktree:
  doc_build_dir: docs_build

on:
  push:
    # PR merge to these branches triggers this workflow
    branches: [ master, stable_1.0 ]

jobs:

  pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # TODO: Understand if this is needed
        fetch-depth: 0  # Required for pushing to the repo
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Set up development environment
      run: |
        make develop
    - name: Build documentation
      run: |
        ${{ env.doc_build_cmd }}
    - name: Set up gh-pages worktree
      run: |
         git worktree add gh-pages gh-pages
         bash -c "cd gh-pages; git fetch"
    - name: Sync documentation to gh-pages worktree
      # The file .gh-pages-exclude defines files to be excluded from the sync
      run: |
         rm -rf gh-pages/*
         rm -rf gh-pages/.doctrees
         rm -f gh-pages/.buildinfo
         ls -al gh-pages
         rsync -a --exclude-from=.gh-pages-exclude ${{ env.doc_build_dir }}/ gh-pages/
    - name: Commit changes in the gh-pages branch locally
      # The git config can specify any user name and email
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        bash -c "cd gh-pages; git add .; git status; git commit -m 'Docs update from PR with commit ${{ github.SHA }}'; true"
    - name: Push gh-pages branch to upstream repo
      uses: ad-m/github-push-action@master
      # From https://github.com/marketplace/actions/github-push
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        directory: gh-pages
