# This GitHub workflow will update the tags of development branches when these
# branches are updated.
# Keep these tags consistent with the pages.yml workflow and with the
# sphinx-versioning config in docs/conf.py.

# Mapping of dev branches to their tags:
env:
  master: 1.0.0-dev1

name: tags

on:
  push:
    # PR merge to these development branches triggers this workflow
    branches: [ master ]

jobs:

  pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Required for pushing to the repo
    - name: Update the tag for the development branch
      run: |
        git checkout ${{ github.ref }}
        echo git tag -f ${{ env.${{ github.ref }} }}
    # - name: Push tags to upstream repo
    #   uses: ad-m/github-push-action@master
    #   # From https://github.com/marketplace/actions/github-push
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: ${{ github.ref }}
    #     tags: true
